language: c
os: linux
compiler: gcc
install : make
script :
    - ./eval_expr "1 + 1"
    - ./eval_expr "545 * 43"
    - ./eval_expr "42 % 2"
    - ./eval_expr "(4 * 6) + (43 * 4) / ((34 + 4) * 6) % 2"
    - ./eval_expr "ER5 + 3"
after_script: make clean
